#!/bin/sh
WATER="$WATER" STIR="$STIR" awk '{for(i=length(ENVIRON["WATER"]),j=length(ENVIRON["STIR"]),a=b=c=0;i||j;a=int(substr(ENVIRON["WATER"],--i+1,1),36),b=int(substr(ENVIRON["STIR"],--j+1,1),36),x=int((a+b+c)%36),c=int((a+b+c)/36))printf substr("0123456789abcdefghijklmnopqrstuvwxyz",x+1,1)}'
