#!/bin/sh
WATER="$WATER" STIR="$STIR" echo "ibase=36;obase=36;$(echo "$WATER+ $STIR" | tr 'waterstir.' '0123456789abcdefghijklmnopqrstuvwxyz') " | bc | tr '0123456789abcdefghijklmnopqrstuvwxyz' 'bestchol.'
